# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79b8a52d7e7a3836f22b31797f13a64d7c070a6326ec5a450e0b46385e09aea5c3c08385d7adeb89b6cd5ef4cca9d6dea236261f7cce4e333c4a8f189e44197f

test:
  secret_key_base: ded36d7fc8389b6ceb67981ac253e7b64a5cdac9a285c711b5cd12d1c30a7a4821111ce8ecdcfceb1e69ce082b035581e2c84ead1d834c13c87715a0409a724b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
